name: Lifesteal
version: '2.0'
main: com.Lino.lifesteal.Lifesteal
api-version: '1.21'
author: Lino
description: Steal the player life!

commands:
  lifesteal:
    description: Main Lifesteal command
    usage: /lifesteal help
    aliases: [ls]

permissions:
  lifesteal.admin:
    description: Administrator permission
    default: op
  lifesteal.reload:
    description: Permission to reload the plugin
    default: op